server.port: 8085

my:
   greeting: Hello world
   list:
      values: one,two,three


db:
   values: "{username:'wiss', password:'wiss2'}"
   host: 127.0.0.1
   port: 4000

management.endpoints.web.exposure.include: "*"

spring.config.import: "optional:configserver:"
spring.cloud.config.uri: http://localhost:8086

spring.application.name: spring-boot-config
